refactor: use for loop for downloads

diff --git a/bin/install-core b/bin/install-core
--- a/bin/install-core
+++ b/bin/install-core
@@ -37,7 +37,7 @@ export DOTFILES=$SOURCE/dotfiles
 export LOCAL_DIR=$DOTFILES/.local
 
 DOWNLOAD_DIR=$HOME/.local/share/bitcoin-core
-BITCOIN_CORE_SOURCE_DOMAIN=(
+BITCOIN_CORE_SOURCE_DOMAINS=(
     "6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion" #Tor onion service
     "bitcoincore.org" #clearnet
 )
@@ -126,12 +126,16 @@ mkdir -p "$DOWNLOAD_DIR"
 # Download Bitcoin core checksums and signatures in background
 (
     cd "$DOWNLOAD_DIR"
-    wget --tries=1 --no-host-directories --cut-dirs=1 --recursive \
-        #--level=1 --accept=SHA256SUMS* --include-directories=bin \
-        #"https://${BITCOIN_CORE_SOURCE_DOMAIN[0]}/en/download/" ||
-    wget --no-host-directories --cut-dirs=1 --recursive \
-        --level=1 --accept=SHA256SUMS* --include-directories=bin \
-        "https://${BITCOIN_CORE_SOURCE_DOMAIN[1]}/en/download/"
+    for domain in ${BITCOIN_CORE_SOURCE_DOMAINS[*]}; do
+        wget --tries=1 --no-host-directories --cut-dirs=1 --recursive \
+            --level=1 --accept=SHA256SUMS* --include-directories=bin \
+            "https://${domain}/en/download/" && break
+    done
+
+    if [ $? -ne 0 ]; then
+        echo "Both wget commands failed."
+        exit 1
+    fi
 ) & sig_dl=$!
 # TODO FIXME uncomment the onion service when bitcoincore.org fixes their service.
 # Download Bitcoin Core in background to the destination directory
@@ -141,12 +145,16 @@ mkdir -p "$DOWNLOAD_DIR"
         sleep 1
     done
     cd "$DOWNLOAD_DIR"
-    #wget --continue --tries=1 --no-host-directories --cut-dirs=1 --recursive \
-        #--level=1 --accept=x86_64-linux-gnu.tar.gz --include-directories=bin \
-        #"http://${BITCOIN_CORE_SOURCE_DOMAIN[0]}/en/download/" ||
-    wget --continue --no-host-directories --cut-dirs=1 --recursive \
-        --level=1 --accept=x86_64-linux-gnu.tar.gz --include-directories=bin \
-        https://${BITCOIN_CORE_SOURCE_DOMAIN[1]}/en/download/
+    for domain in ${BITCOIN_CORE_SOURCE_DOMAINS[*]}; do
+        wget --continue --tries=1 --no-host-directories --cut-dirs=1 --recursive \
+            --level=1 --accept=x86_64-linux-gnu.tar.gz --include-directories=bin \
+            "http://${domain}/en/download/" && break
+    done
+
+    if [ $? -ne 0 ]; then
+        echo "Both wget commands failed."
+        exit 1
+    fi
 ) & core_download=$!
 
 # Download chain parameters in background
