gracefully tolerate Persistence already setup

diff --git a/bin/persistent-setup b/bin/persistent-setup
--- a/bin/persistent-setup
+++ b/bin/persistent-setup
@@ -26,66 +26,84 @@
 
 # For security reviewing this use: https://explainshell.com/ for commands that are unclear.
 
-timeout=5	# initial spaced repetition delay in seconds
-
 # Display welcome message
-zenity --title='Welcome to Bails' --info \
+[ -f $HOME/.local/share/*/b ] || zenity --title='Welcome to Bails' --info \
     --text="Thank you for choosing Bails, a self-custodial Bitcoin Core wallet and full node.\n\nDuring this initial setup process, we will guide you through the necessary steps\nto ensure a smooth experience. Let's get started!" \
     --no-wrap --ok-label='Continue' $ICON --icon-name=bails128
 
-# Choose passphrase
-zenity --warning --title='Choose a strong passphrase' \
-    --text='It is important to select a strong passphrase to protect your Bitcoin data.\n\nWe recommend using a suggested passphrase from the Persistent Storage dialog.' \
-    --ok-label='I Will Use a Suggested Passphrase' --icon-name=tails-persistent-storage --no-wrap $ICON
-zenity --warning --title='Write your passphrase down' \
-    --text='It is impossible to recover your passphrase if you forget it!\n\nTo help you remember your passphrase, you can write it on a piece of paper, store it in a sealed envelope in your wallet for a few days, and destroy it once you know it well. Write on a hard surface to avoid leaving an imprint of the secret.' \
-    --ok-label='I Will Write My Passphrase Down' --icon-name=org.gnome.gedit --width=530 $ICON
-
-# Persistent storage creation
-until [ -b '/dev/mapper/TailsData_unlocked' ]; do
-        sleep 10
-        notify-send --icon=bails128 'Important: Use a suggested passphrase. To help remember:' 'Create a mental image or mnemonic using the words, in order.\n\nIt might be a story, scenario, or sentence that you will be able to remember and that can remind you of the particular words you chose, in order.'
-done & notifying+=($!)
-
-until [ -b '/dev/mapper/TailsData_unlocked' ]; do
-    grep --count 'python3 /usr/local/lib/tps-frontend' <<< $(ps -ef) - >/dev/null ||
-        { tails-persistent-storage & notify-send --icon=tails-persistent-storage 'Click Continue to create a Persistent Storage'; }
-    sleep 1
-done
-
-# Clear notifications
-kill ${notifying[*]} &>/dev/null
-dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.panel.statusArea.dateMenu._messageList._sectionList.get_children().forEach(s => s.clear());'
-
-# Memorization help
-until {
-    zenity --info --title='Spaced repetition trainer' \
-        --text='Enter the <b>exact</b> same passphrase from Persistent Storage so Bails can help you memorize it.' \
-        --ok-label='I Will Enter the Exact Same Passphrase' --ellipsize $ICON
-    python3 -c 'from bails import set_pass
-box = set_pass.SimplePassphraseDialog(None,"Enter the passphrase of your Persistent Storage")
+# check for already unlocked Persistent Storage
+if [ -b '/dev/mapper/TailsData_unlocked' ]; then
+    # Check for existing Persistent Storage passphrase if setup never completed
+    [ -f $HOME/.local/share/*/b ] || until python3 -c 'from bails import set_pass
+box = set_pass.SimplePassphraseDialog(None,"Enter your existing Persistent Storage passphrase")
 if box.passphrase:
     print(box.passphrase+"\n"+box.passphrase)
 else:
-    print("\n")' 2>/dev/null | passwd
-}; do
-    zenity --warning --text='No passphrase was entered.' --title="Spaced repetition trainer" \
-        --ok-label='Try Again' --ellipsize
-done
+    print("\n")' 2>/dev/null | passwd; do
+        zenity --error --title="Error" --text="Existing Persistent Storage passphrase is required. Please provide the passphrase to continue." $ICON
+    done
+else
+    # Choose passphrase
+    zenity --warning --title='Choose a strong passphrase' \
+        --text='It is important to select a strong passphrase to protect your Bitcoin data.\n\nWe recommend using a suggested passphrase from the Persistent Storage dialog.' \
+        --ok-label='I Will Use a Suggested Passphrase' --icon-name=tails-persistent-storage --no-wrap $ICON
+    zenity --warning --title='Write your passphrase down' \
+        --text='It is impossible to recover your passphrase if you forget it!\n\nTo help you remember your passphrase, you can write it on a piece of paper, store it in a sealed envelope in your wallet for a few days, and destroy it once you know it well. Write on a hard surface to avoid leaving an imprint of the secret.' \
+        --ok-label='I Will Write My Passphrase Down' --icon-name=org.gnome.gedit --width=530 $ICON
 
-# Spaced repetition training loop
-spaced-repetition &
+    # Persistent storage creation
+    until [ -b '/dev/mapper/TailsData_unlocked' ]; do
+            sleep 10
+            notify-send --icon=bails128 'Important: Use a suggested passphrase. To help remember:' 'Create a mental image or mnemonic using the words, in order.\n\nIt might be a story, scenario, or sentence that you will be able to remember and that can remind you of the particular words you chose, in order.'
+    done & notifying+=($!)
 
-# Display memorization tips
-zenity --info --title='Tips for your new passphrase' \
-    --text="You will be prompted periodically to enter your passphrase as spaced repetition training. Practice entering the passphrase <i>daily at first and then at least once a week</i>  to commit it to memory.\n\nIt is essential to keep your passphrase safe and not use it for any other accounts. If you wrote it down, store it in a secure location away from your Bails USBs and destroy it once you memorize it." \
-    --ok-label='I Will Destroy It Once Memorized' --width=640 $ICON
-    
+    until [ -b '/dev/mapper/TailsData_unlocked' ]; do
+        grep --count 'python3 /usr/local/lib/tps-frontend' <<< $(ps -ef) - >/dev/null ||
+            { tails-persistent-storage & notify-send --icon=tails-persistent-storage 'Click Continue to create a Persistent Storage'; }
+        sleep 1
+    done
+
+    # Clear notifications
+    kill ${notifying[*]} &>/dev/null
+    dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.panel.statusArea.dateMenu._messageList._sectionList.get_children().forEach(s => s.clear());'
+
+    # Memorization help
+    until {
+        zenity --info --title='Spaced repetition trainer' \
+            --text='Enter the <b>exact</b> same passphrase from Persistent Storage so Bails can help you memorize it.' \
+            --ok-label='I Will Enter the Exact Same Passphrase' --ellipsize $ICON
+        python3 -c 'from bails import set_pass
+    box = set_pass.SimplePassphraseDialog(None,"Enter the passphrase of your Persistent Storage")
+    if box.passphrase:
+        print(box.passphrase+"\n"+box.passphrase)
+    else:
+        print("\n")' 2>/dev/null | passwd
+    }; do
+        zenity --warning --text='No passphrase was entered.' --title="Spaced repetition trainer" \
+            --ok-label='Try Again' --ellipsize
+    done
+
+fi
+[ -f $HOME/.local/share/*/b ] || {
+    # Spaced repetition training loop
+    spaced-repetition &
+
+    # Display memorization tips
+    zenity --info --title='Tips for your new passphrase' \
+        --text="You will be prompted periodically to enter your passphrase as spaced repetition training. Practice entering the passphrase <i>daily at first and then at least once a week</i>  to commit it to memory.\n\nIt is essential to keep your passphrase safe and not use it for any other accounts. If you wrote it down, store it in a secure location away from your Bails USBs and destroy it once you memorize it." \
+        --ok-label='I Will Destroy It Once Memorized' --width=640 $ICON
+}
 # Checking features of the Persistent Storage
-zenity --info --title='Features of the Persistent Storage' \
-    --text='In the Persistent Storage application below, scroll\nand click the toggle to turn on necessary features.' \
-    --icon-name=tails-persistent-storage $ICON --no-wrap &
-sleep 4
+if /usr/local/lib/tpscli is-active PersistentDirectory && \
+    /usr/local/lib/tpscli is-active GnuPG && \
+    /usr/local/lib/tpscli is-active Dotfiles; then
+        :
+else
+    zenity --info --title='Features of the Persistent Storage' \
+        --text='In the Persistent Storage application below, scroll\nand click the toggle to turn on necessary features.' \
+        --icon-name=tails-persistent-storage $ICON --no-wrap &
+    sleep 4
+fi
 until /usr/local/lib/tpscli is-active PersistentDirectory && \
     /usr/local/lib/tpscli is-active GnuPG && \
     /usr/local/lib/tpscli is-active Dotfiles; do
