move passphrase set to outside the loop

diff --git a/bin/persistent-setup b/bin/persistent-setup
--- a/bin/persistent-setup
+++ b/bin/persistent-setup
@@ -58,12 +58,12 @@ else:
                   --width=600 $ICON --ok-label='Restart Now'
                 exit 1
             fi
-            unset entropy
-            # Change user account password to Persistent Storage passphrase for spaced repetition practice.
-            echo -e "$existing_passphrase\n$existing_passphrase" | passwd || echo "FAILURE to change passphrase"
         fi
             zenity --error --title="Error" --text="Existing Persistent Storage passphrase is required. Please provide the passphrase to continue." $ICON
     done
+    unset entropy
+     # Change user account password to Persistent Storage passphrase for spaced repetition practice.
+    printf "$existing_passphrase\n$existing_passphrase" | passwd || echo "FAILURE to change passphrase"
 else
     # Choose passphrase
     zenity --warning --title='Choose a strong passphrase' \
