Persist the spaced-repetition feature across restarts of Bails

diff --git a/bails/.local/bin/persistent-setup b/bails/.local/bin/persistent-setup
--- a/bails/.local/bin/persistent-setup
+++ b/bails/.local/bin/persistent-setup
@@ -29,15 +29,20 @@ export XDG_STATE_HOME="/live/persistence/TailsData_unlocked/dotfiles/.local/stat
 SET_UP="$XDG_STATE_HOME/tps_is_set_up"
 
 # Check if user password is already set
-passwd_unset=$(passwd -S "$USER" | grep -c NP)
+PASSWD_UNSET=$(passwd -S "$USER" | grep -c NP)
 
 # Display welcome message
-[ -f $SET_UP ] || zenity --title='Welcome to Bails' --info \
+[ -f $SET_UP ] || { zenity --title='Welcome to Bails' --info \
     --text="Thank you for choosing Bails, a self-custodial Bitcoin wallet and full node.\n\nDuring this initial setup process, we will guide you through the necessary steps\nto ensure a smooth experience. Let's get started!" \
     --no-wrap --ok-label='Continue' "$ICON" --icon-name=bails128
+    mkdir -p "$HOME/.local/state/bails"
+    cd "$HOME/.local/state/bails" || exit 1
+    fallocate -l 32MiB Persistent_Storage.img
+}
 
 # Check for already unlocked Persistent Storage
-pgrep -f spaced-repetition || if /usr/local/lib/tpscli is-unlocked; then
+
+pgrep -f spaced-repetition > /dev/null || if /usr/local/lib/tpscli is-unlocked; then
     # Check for existing Persistent Storage passphrase
     until [ -f $SET_UP ]; do
         existing_passphrase="$(python3 -c 'from bails import set_pass
@@ -49,6 +54,10 @@ else:
         if [ -z "$existing_passphrase" ]; then
             zenity --error --title="Error" --text="Existing Persistent Storage passphrase is required. Please provide the passphrase." "$ICON"
         else
+            if ((PASSWD_UNSET)); then
+                # Change user account password to Persistent Storage passphrase for spaced repetition practice.
+                printf '%s\n%s' "$existing_passphrase" "$existing_passphrase" | passwd || echo "FAILURE to change passphrase"
+            fi
             # Estimate passphrase entropy to see if we can proceed
             entropy=$(keepassxc-cli estimate "${existing_passphrase// /}" | cut -f2 | tr -C -d '[:digit:]')
             if ((entropy >= 65000)); then
@@ -63,11 +72,8 @@ else:
             systemctl reboot
         fi
     done
-    unset entropy
-    [ -f $SET_UP ] || if ((passwd_unset)); then
-        # Change user account password to Persistent Storage passphrase for spaced repetition practice.
-        printf '%s\n%s' "$existing_passphrase" "$existing_passphrase" | passwd || echo "FAILURE to change passphrase"
-    fi
+    printf '%s' "$existing_passphrase" | /sbin/cryptsetup --batch-mode luksFormat Persistent_Storage.img
+    unset entropy existing_passphrase
 else
     printf '\033]2;Setup the Persistent Storage\a'
     # Choose passphrase
@@ -95,28 +101,27 @@ Write on a hard surface to avoid leaving an imprint of the secret.' \
     # Clear notifications
     kill "${notifying[@]}" &>/dev/null
 
+
     # Memorization help
-    ((passwd_unset)) && \
     until {
         zenity --info --title='Spaced repetition trainer' \
             --text='Enter the <b>exact</b> same passphrase from Persistent Storage so Bails can help you memorize it.' \
             --ok-label='I Will Enter the Exact Same Passphrase' --ellipsize "$ICON"
         python3 -c 'from bails import set_pass
+import subprocess
+
 box = set_pass.SimplePassphraseDialog(None,"Enter Persistent Storage passphrase")
 if box.passphrase:
-    print(box.passphrase+"\n"+box.passphrase)
-else:
-    print("\n")' 2>/dev/null | passwd
+    print(box.passphrase)' 2>/dev/null | /sbin/cryptsetup --batch-mode luksFormat Persistent_Storage.img
     }; do
         zenity --warning --text='No passphrase was entered.' --title="Spaced repetition trainer" \
             --ok-label='Try Again' --ellipsize
     done
-
 fi
-if ((passwd_unset)) && ! [ -f "$SET_UP" ]; then
-    # Spaced repetition training loop
-    spaced-repetition &
+# Spaced repetition training
+pgrep spaced-repetition > /dev/null || spaced-repetition &
 
+if ! [ -f "$SET_UP" ]; then
     # Display memorization tips
     zenity --info --title='Tips for your new passphrase' \
             --text="You will be prompted to enter your passphrase as spaced repetition training.\n\nPractice entering your passphrase <i>daily at first and then at least once a week</i>  to commit it to memory.\n
@@ -174,5 +179,7 @@ done
 # Close the Persistent Storage window
 pkill -f "python3 /usr/local/lib/tps-frontend" &>/dev/null
 pkill -f 'zenity --notification' &>/dev/null
-mkdir -vp $XDG_STATE_HOME
+mkdir -vp $XDG_STATE_HOME/bails
+rsync -vP --remove-source-files Persistent_Storage.img $XDG_STATE_HOME/bails/Persistent_Storage.img
 touch $SET_UP
+link-dotfiles
